### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by sudo-bai** [crayonxin2000/NeteaseCloudPlayListDownload#5]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\26584\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 450, in send
    timeout=timeout
  File "C:\Users\26584\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\26584\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='netease-cloud-music-api-gamma-orpin.vercel.app', port=443): Max retries exceeded with url: /login/qr/key (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001107666B5C0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by sudo-bai** [comment]
登录获取二维码时获取失败

**Comment by codeliuyw** [comment]
怎么解决呢
